language: java
jdk: oraclejdk8
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
  - chmod +x gradlew
sudo: true
addons:
  apt:
    packages:
      - oracle-java8-installer